relaunch

diff --git a/.tekton/konflux-components-dev-ms-rpm-pull-request.yaml b/.tekton/konflux-components-dev-ms-rpm-pull-request.yaml
--- a/.tekton/konflux-components-dev-ms-rpm-pull-request.yaml
+++ b/.tekton/konflux-components-dev-ms-rpm-pull-request.yaml
@@ -51,43 +51,44 @@ spec:
       #!/usr/bin/env bash
       set -euxo pipefail
       
-      echo "--- Preparing to generate spec and sources using Skopeo  ---"
-      echo "--- SOURCE_ARTIFACT_URL ${SOURCE_ARTIFACT_URL}  ---"
+      echo "--- Preparing to access source artifact ---"
+      echo "--- SOURCE_ARTIFACT_URL: ${SOURCE_ARTIFACT_URL} ---"
       
       CLEAN_SOURCE_URL=${SOURCE_ARTIFACT_URL#oci:}
-      URL_WITH_GIT_SUFFIX=$(echo "${CLEAN_SOURCE_URL}" | sed 's|@|.git@|')
-      echo "Corrected artifact URL for inspection: ${URL_WITH_GIT_SUFFIX}"
       
-      echo "Waiting for manifest to be available for ${URL_WITH_GIT_SUFFIX}..."
+      echo "Waiting for manifest to be available for ${CLEAN_SOURCE_URL}..."
       
       # Retry for up to 2 minutes to solve registry race conditions
-      for i in {1..12}; do
-        if skopeo inspect "docker://${URL_WITH_GIT_SUFFIX}" > /dev/null; then
+      for i in {1..3}; do
+        if skopeo inspect "docker://${CLEAN_SOURCE_URL}" > /dev/null; then
           echo "Manifest is now available!"
-          break # Exit the loop and continue the script
+          break
         fi
         if [ "$i" -eq 12 ]; then
-          echo "Error: Timed out waiting for manifest."
-        exit 1
+          echo "Error: Timed out waiting for manifest." >&2
+          exit 1
         fi
         echo "Manifest not found. Retrying in 10 seconds..."
         sleep 10
       done
       
-      echo "--- Preparing to generate spec and sources using Skopeo   ---"
-      
+      echo "--- Extracting original git repository ---"
       mkdir -p original-repo
       skopeo copy "docker://${CLEAN_SOURCE_URL}" "dir:./original-repo"
       echo "Original repo extracted using Skopeo."
       
-      cd original-repo
+      echo "--- Changing to the component directory to run generator script ---"
+      cd original-repo/rpms/microshift-gitops
+
       ./generic-pre-build-script.sh
-      cd ..
       echo "Generator script executed successfully."
       
+      cd ../../..
+      
+      echo "--- Preparing new source artifact with generated spec and sources ---"
       mkdir workdir
       cp original-repo/rpms/microshift-gitops/microshift-gitops.spec ./workdir/
-      cp original-repo/argo-cd-sources.tar.gz ./workdir/
+      cp original-repo/rpms/microshift-gitops/argo-cd-sources.tar.gz ./workdir/
       
       cd workdir
       sha512sum *.tar.gz > sources
@@ -95,6 +96,7 @@ spec:
       cd ..
       echo "'sources' file created."
       
+      echo "--- Pushing manipulated source artifact to registry ---"
       MODIFIED_ARTIFACT_URL="${OCI_STORAGE_URL}.sources:pre-build-$(date +%s)"
       skopeo copy "dir:./workdir" "docker://${MODIFIED_ARTIFACT_URL}" --digestfile digest.txt
       
