relaunch

diff --git a/.tekton/konflux-components-dev-ms-rpm-pull-request.yaml b/.tekton/konflux-components-dev-ms-rpm-pull-request.yaml
--- a/.tekton/konflux-components-dev-ms-rpm-pull-request.yaml
+++ b/.tekton/konflux-components-dev-ms-rpm-pull-request.yaml
@@ -52,16 +52,36 @@ spec:
       set -euxo pipefail
       
       echo "--- Preparing to generate spec and sources using Skopeo  ---"
+      echo "--- SOURCE_ARTIFACT_URL ${SOURCE_ARTIFACT_URL}  ---"
+      
+      CLEAN_SOURCE_URL=${SOURCE_ARTIFACT_URL#oci:}
+      
+      echo "Waiting for manifest to be available for ${CLEAN_SOURCE_URL}..."
+      
+      # Retry for up to 2 minutes to solve registry race conditions
+      for i in {1..12}; do
+        if skopeo inspect "docker://${CLEAN_SOURCE_URL}" > /dev/null; then
+          echo "Manifest is now available!"
+          break # Exit the loop and continue the script
+        fi
+        if [ "$i" -eq 12 ]; then
+          echo "Error: Timed out waiting for manifest."
+        exit 1
+        fi
+        echo "Manifest not found. Retrying in 10 seconds..."
+        sleep 10
+      done
+      
+      echo "--- Preparing to generate spec and sources using Skopeo ---"
       
       mkdir -p original-repo
-      CLEAN_SOURCE_URL=${SOURCE_ARTIFACT_URL#oci:}
       skopeo copy "docker://${CLEAN_SOURCE_URL}" "dir:./original-repo"
       echo "Original repo extracted using Skopeo."
       
       cd original-repo
       ./generic-pre-build-script.sh
       cd ..
-      echo "Generator script executed successfully. "
+      echo "Generator script executed successfully."
       
       mkdir workdir
       cp original-repo/rpms/microshift-gitops/microshift-gitops.spec ./workdir/
